# .mockery.yaml
with-expecter: true
all: false
recursive: true
packages:
  github.com/lostmyescape/link-shortener/url-shortener/internal/http-server/handlers/redirect:
    config:
      dir: internal/http-server/handlers/redirect
      output: internal/http-server/handlers/redirect/mocks
      outpkg: mocks
