// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// URLSearcher is an autogenerated mock type for the URLSearcher type
type URLSearcher struct {
	mock.Mock
}

// GetUrl provides a mock function with given fields: alias
func (_m *URLSearcher) GetUrl(alias string) (string, error) {
	ret := _m.Called(alias)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(alias)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(string)
		} else {
			r0 = ""
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(alias)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewURLSearcher interface {
	mock.TestingT
	Cleanup(func())
}

// NewURLSearcher creates a new instance of URLSearcher. It also registers a testing interface on the mock and a cleanup function to assert the mock's expectations.
func NewURLSearcher(t mockConstructorTestingTNewURLSearcher) *URLSearcher {
	mock := &URLSearcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
